matches:
- trigger: btw
  replacement:
    type: Static
    text: by the way
    propagate_case: false
- trigger: date
  replacement:
    type: Dynamic
    action: '{{date}}'
backend:
  key_delay: 10
