name: Textra Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  create-release:
    if: contains(github.event.head_commit.message, 'release')
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Determine Release Tag
        id: determine_release_tag
        shell: powershell
        run: |
          $timestamp = Get-Date -Format "yyyy.MM.dd.HHmmss"
          echo "RELEASE_TAG=v$timestamp" >> $env:GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: textra 🚀 release ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Rust Project
        run: cargo build --release
        working-directory: ./src  # Adjust this to the correct path where Cargo.toml is located

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./src/target/release/textra.exe  # Adjust if necessary
          asset_name: textra.exe
          asset_content_type: application/octet-stream

      - name: Publish to crates.io
        run: cargo publish
        working-directory: ./src  # Adjust this to the correct path where Cargo.toml is located
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
