name: Textra Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  create-release:
    if: contains(github.event.head_commit.message, 'release')
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Rust Project
        run: cargo build --release --bin textra
        working-directory: ./src  # Adjust this to the correct path where Cargo.toml is located

      - name: Custom Release Script
        shell: bash
        run: |
          # Create a release tag
          RELEASE_TAG="v$(date +'%Y.%m.%d.%H%M%S')"
          echo "Creating release with tag $RELEASE_TAG"
          
          # Create a GitHub release
          API_JSON=$(printf '{"tag_name": "%s", "target_commitish": "master", "name": "textra 🚀 release %s", "draft": false, "prerelease": false}' $RELEASE_TAG $RELEASE_TAG)
          RESPONSE=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "$API_JSON" https://api.github.com/repos/${{ github.repository }}/releases)
          
          # Extract the upload URL
          UPLOAD_URL=$(echo "$RESPONSE" | jq -r .upload_url | sed -e "s/{?name,label}//")
          if [ "$UPLOAD_URL" == "null" ]; then
            echo "Failed to create release"
            exit 1
          fi
          
          # Upload the .exe file to the release
          EXE_PATH="./src/target/release/textra.exe"  # Adjust if necessary
          curl -s --data-binary @"$EXE_PATH" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            "$UPLOAD_URL?name=textra-windows.exe"
          
          echo "Release and upload completed successfully"

      - name: Publish to crates.io
        run: cargo publish
        working-directory: ./src  # Adjust this to the correct path where Cargo.toml is located
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
